sudo: false
language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install rednose
  - pip install nose
  - pip install mock
script: nosetests
after_success:
  - pip install coveralls
  - coveralls
